@base_url = http://localhost:8080/api/user

# CREATE happy path
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "email": "valid@gmail.com",
    "password": "password"
}

###

# CREATE blank email
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "email": "",
    "password": "password"
}

###

# CREATE invalid email
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "email": "not an email",
    "password": "password"
}

###

# CREATE blank password
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "email": "email@email.com",
    "password": ""
}

###

# CREATE duplicate email
POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "email": "peaveybryan03@gmail.com",
    "password": "password"
}